### ISSUE TITLE
Get Started Button Bug

### ISSUE THREAD

**Issue by wangj19** [ClemsonRSRG/beginToReason2#133]
The get started button on the main page seemed does not work.

**Comment by rhit-hurtigna** [comment]
Yep, that's a link to something from the old system that I haven't got around to rerouting yet. If you'd like, you can fix it - a good place to direct that link to would be tutor:classes.

**Comment by rhit-hurtigna** [comment]
I made a commit that should delete all references to the old broken link - now the button links to login when there's no user, and class view when there is. It'll be live once my pull request goes through.
